repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: pytest
        types: [python]
        pass_filenames: false
        always_run: true

      - id: pytest-cov
        name: pytest
        stages: [push]
        language: system
        entry: pytest --cov --cov-fail-under=70
        types: [python]
        pass_filenames: false
