repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: pytest
        types: [python]
        pass_filenames: false
        always_run: true

      - id: pytest-cov
        name: pytest
        stages: [push]
        language: system
        entry: pytest --cov --cov-fail-under=70
        types: [python]
        pass_filenames: false
